[package]
name = "near"
version = "0.1.0"
authors = [
    "akorchyn <artur.yurii.korchynskyi@gmail.com>",
    "frol <frolvlad@gmail.com>",
    "Near Inc <hello@nearprotocol.com>",
]
license = "MIT OR Apache-2.0"
edition = "2021"
repository = "https://github.com/akorchyn/near-api-rs"
description = "The near protocol API that helps to interact with NEAR Protocol"

[dependencies]
borsh = "1.5"
async-trait = "0.1"

reqwest = { version = "0.12", features = ["blocking", "json"] }
futures = "0.3"
# Ad-hoc fix for compilation errors (rustls is used instead of openssl to ease the deployment avoiding the system dependency on openssl)
openssl = { version = "0.10", features = ["vendored"] }

bip39 = { version = "2.0.0", features = ["rand"] }
ed25519-dalek = { version = "2", default-features = false }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.57"
slipped10 = { version = "0.4.6" }
url = { version = "2", features = ["serde"] }
tokio = { version = "1.0", default-features = false, features = ["time"] }

thiserror = "1"

near-ledger = { version = "0.8.1", optional = true }

near-crypto = "0.25"
near-primitives = "0.25"
near-jsonrpc-client = "0.12"
near-jsonrpc-primitives = "0.25"
near-contract-standards = "5.4"
near-sdk = "5.4"

near-account-id = "1.0.0"
near-gas = { version = "0.3", features = ["serde", "borsh"] }
near-token = { version = "0.3", features = ["serde", "borsh"] }
near-socialdb-client = "0.6"

near-abi = "0.4.2"
zstd = "0.13"

keyring = { version = "3.2", features = [
    "apple-native",
    "windows-native",
    "sync-secret-service",
    "vendored",
] }

near-workspaces = { version = "0.12.0", optional = true }


[features]
default = ["ledger"]
ledger = ["near-ledger"]
workspaces = ["dep:near-workspaces"]

[dev-dependencies]
tokio = { version = "1.0", default-features = false, features = ["full"] }
near = { path = ".", features = ["workspaces"] }
