[package]
name = "near-api-rs"
version = "0.1.0"
authors = ["FroVolod <frol_off@meta.ua>", "Near Inc <hello@nearprotocol.com>"]
license = "MIT OR Apache-2.0"
edition = "2021"
repository = "https://github.com/akorchyn/near-api-rs"
description = "The near protocol API that helps to interact with NEAR Protocol"

[dependencies]
anyhow = "1.0"
async-trait = "0.1"
inquire = "0.7"
strum = { version = "0.24", features = ["derive"] }
strum_macros = "0.24"
smart-default = "0.7.1"
derive_more = "0.99.9"
easy-ext = "1"

reqwest = { version = "0.12", features = ["blocking", "json"] }
tokio = { version = "1.0", default-features = false, features = [
    "rt-multi-thread",
] }
futures = "0.3"
# Ad-hoc fix for compilation errors (rustls is used instead of openssl to ease the deployment avoiding the system dependency on openssl)
openssl = { version = "0.10", features = ["vendored"] }

bip39 = { version = "2.0.0", features = ["rand"] }
bs58 = "0.5"
ed25519-dalek = { version = "2", default-features = false }
hex = "0.4.2"
linked-hash-map = { version = "0.5", features = ["serde_impl"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.57"
toml = "0.8"
dirs = "5"
shellexpand = "3"
slipped10 = { version = "0.4.6" }
url = { version = "2", features = ["serde"] }
open = "5"
shell-words = "1"
cargo-util = "0.1.1"
indicatif = "0.17.8"
tracing = "0.1.40"
tracing-indicatif = "0.3.6"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

wasmparser = "0.211"

semver = { version = "1.0.4", optional = true }
self_update = { version = "0.40.0", features = [
    "archive-tar",
    "compression-flate2",
], optional = true }

thiserror = "1"

bytesize = "1.1.0"
prettytable = "0.10.0"
textwrap = "0.16.1"

near-ledger = { version = "0.7.1", optional = true }

near-crypto = "0.23"
near-primitives = "0.23"
near-jsonrpc-client = "0.10.1"
near-jsonrpc-primitives = "0.23"

near-gas = { version = "0.2.3", features = [
    "serde",
    "borsh",
    "interactive-clap",
] }
near-token = { version = "0.2.0", features = [
    "serde",
    "borsh",
    "interactive-clap",
] }
near-socialdb-client = "0.3.1"

near-abi = "0.4.2"
zstd = "0.13"

keyring = "2.0.5"
interactive-clap = "0.2.10"
interactive-clap-derive = "0.2.10"

rust_decimal = "1.35.0"
